version: '3.8'

services:
  proxy:
    image: nginx:alpine
    ports:
      - '180:180'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: 'unless-stopped'
    networks:
      - backend

  nest:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 3000
    restart: 'unless-stopped'
    depends_on:
      - database
    networks:
      - backend

  database:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: root
    ports:
      - 15432:5432
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data
    depends_on:
      - proxy
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  data:
