version: "3.8"

services:
  database:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: user
    ports:
      - 15432:5432
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - data:/var/lib/postgresql/data

volumes:
  data:
